name: Mayank Github actions test
on: 
  push: 
    branches: master

jobs: 
  testing: 
    name: Testing Phase
    runs-on: ubuntu-latest
    steps: 
    - name: checkout
      uses: actions/checkout@v4

    - name: First step
      run: | 
        echo "Welcome to Github Actions"
        ls -lart
        cat index.html

    - name: ASCII Artwork
      run : cowsay -f dragon "Run for Cover, I am A Dragon.."  >> dragon.txt


