name: generating ascii artwork

on: push

jobs: 
  myartwork:
    runs-on: ubuntu-latest
    steps:
    - name: install of cowsay
      run: apt install -y cowsay

    - name: running commands
      run: cowsay -f dragon "Run for Cover, I am A Dragon.."  >> dragon.txt

    - name: testing file
      run: | 
        cat dragon.txt 
        grep -i dragon dragon.txt

    - name: list all files
      run: ls -lart

