name: Matrix Configurations
on:
    push:
    workflow_dispatch: 

jobs:
  deploy-on-ubuntu:
    runs-on: ubuntu-latest
    steps: 
    - name: Getting docker details
      run: docker info

    - name: crreate a container
      run: docker run hello-world

  
  deploy-on-windows:
    runs-on: windows-latest
    steps: 
    - name: Getting docker details
      run: docker info

    - name: crreate a container
      run: docker run hello-world