name: Matrix Configurations
on:
    push:
    workflow_dispatch: 

jobs:
  deploy:
    strategy:
        matrix: 
          os: [ubuntu-latest, ubuntu-22.04, windows-latest]
          images: [hello-world, debian]
    runs-on: "${{ matrix.os }}"
    steps: 
    - name: Getting docker details
      run: docker info
    - name: Creating multiple container using diff images on diff os
      run: docker run ${{ matrix.images }}
